apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver_k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver_k8s
  template:
    metadata:
      labels:
        app: httpserver_k8s
    spec:
      containers:
        - name: httpserver_k8s
          image: isziyang/httpserver:v3.0
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "1.0"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: log-config
                  key: LOG_LEVEL
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /localhost/healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /localhost/healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "kill httpserver_k8s"]
      terminationGracePeriodSeconds: 30